export const UPDATE_PLAYER_NAME = 'UPDATE_PLAYER_NAME';
export const SHIP_POSITIONING = 'SHIP_POSITIONING';
export const UPDATE_SHIP_QUANTITY = 'UPDATE_SHIP_QUANTITY';
export const UPDATE_BOARD = 'UPDATE_BOARD';
